CREATE DEFINER=`root`@`localhost` PROCEDURE `delete_book`(IN bIdIn INT, IN uIdIn INT)
    SQL SECURITY INVOKER
BEGIN
	IF EXISTS(SELECT * FROM	T_BOOK WHERE bId = bIdIn AND uId = uIdIn)
		THEN DELETE	FROM T_WRITES	WHERE	T_WRITES.bId = bIdIn;
             DELETE FROM T_REVIEW	WHERE	T_REVIEW.bId = bIdIn;
             DELETE FROM T_BOOK		WHERE	T_BOOK.bId = bIdIn;
             DELETE FROM T_AUTHOR	WHERE	T_AUTHOR.aId NOT IN (SELECT T_WRITES.aId FROM T_WRITES);
		ELSE SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Not your book';
	END IF;
END